services:
  app:
    build: .
    container_name: laravel_app
    working_dir: /var/www/html
    volumes:
      - .:/var/www/html
      - ./docker/supervisor:/etc/supervisor/conf.d
    networks:
      - laravel
    depends_on:
      - db
      - redis
    command: sh -c "supervisord && php-fpm"

  web:
    image: nginx:latest
    container_name: laravel_nginx
    ports:
      - "8000:80"
    volumes:
      - .:/var/www/html
      - ./docker/nginx/default.conf:/etc/nginx/conf.d/default.conf
    depends_on:
      - app
    networks:

      - laravel

  db:
    image: mysql:8
    container_name: laravel_mysql
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: laravel
      MYSQL_USER: laravel
      MYSQL_PASSWORD: secret
    volumes:
      - dbdata:/var/lib/mysql
    networks:
      - laravel

  redis:
    image: redis:alpine
    container_name: laravel_redis
    restart: always
    networks:
      - laravel

  vite:
    image: node:18-alpine
    container_name: laravel_vite
    working_dir: /var/www/html
    volumes:
      - .:/var/www/html
    command: ["sh", "-c", "npm install && npm run dev"]
    ports:
      - "5173:5173"
    networks:
      - laravel

volumes:
  dbdata:

networks:
  laravel:
    driver: bridge
