services:
  app:
    build: 
      context: .
      dockerfile: dockerfile
    container_name: larecta_app
    volumes:
      - .:/var/www
    networks:
      - larecta_network
   

  web:
    image: nginx:latest
    container_name: larecta_nginx
    ports:
      - "8000:80"
    volumes:
      - .:/var/www
      - ./docker/nginx/default.conf:/etc/nginx/conf.d/default.conf
    depends_on:
      - app
    networks:
      - larecta_network

  db:
    image: mysql:8
    container_name: larecta_mysql
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: larecta
      MYSQL_USER: larecta
      MYSQL_PASSWORD: larecta
    volumes:
      - dbdata:/var/lib/mysql
    networks:
      - larecta_network

  redis:
    image: redis:alpine
    container_name: larecta_redis
    restart: always
    networks:
      - larecta_network

  vite:
    image: node:18-alpine
    container_name: larecta_vite
    working_dir: /var/www
    volumes:
      - .:/var/www
    command: ["sh", "-c", "npm install && npm run dev"]
    ports:
      - "5173:5173"
    networks:
      - larecta_network

volumes:
  dbdata:

networks:
  larecta_network:
    driver: bridge
