services:
  app:
    build:
      context: .
      dockerfile: dockerfile
    image: larecta:latest
    container_name: larecta-app
    volumes:
      - .:/var/www
    networks:
      - larecta_network

  web:
    image: nginx:alpine
    container_name: larecta-web
    ports:
      - "8082:80"
    volumes:
      - .:/var/www
      - ./nginx/default.conf:/etc/nginx/conf.d/default.conf
    networks:
      - larecta_network

  larecta-db:
    image: mysql:8
    container_name: larecta-mysql
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: larecta
      MYSQL_USER: larecta
      MYSQL_PASSWORD: larecta
    volumes:
      - db_data:/var/lib/mysql
    networks:
      - larecta_network
    ports:
         - "3308:3306"

networks:
  larecta_network:

volumes:
  db_data: