openapi: 3.0.3
info:
  title: Laravel
  description: ''
  version: 1.0.0
servers:
  -
    url: 'http://localhost:8000'
paths:
  /api/auth/register:
    post:
      summary: 'Yeni bir kullanıcı kaydı oluşturur.'
      operationId: yeniBirKullancKaydOluturur
      description: ''
      parameters: []
      responses: {  }
      tags:
        - Endpoints
      security: []
  /api/auth/login:
    post:
      summary: 'Kullanıcı girişi yapar ve token oluşturur.'
      operationId: kullancGiriiYaparVeTokenOluturur
      description: ''
      parameters: []
      responses: {  }
      tags:
        - Endpoints
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                email:
                  type: string
                  description: 'Must be a valid email address.'
                  example: ike78@example.com
                  nullable: false
                password:
                  type: string
                  description: ''
                  example: quo
                  nullable: false
              required:
                - email
                - password
      security: []
  /api/auth/logout:
    post:
      summary: 'Kullanıcının çıkış yapmasını sağlar ve tüm tokenları siler.'
      operationId: kullancnnkYapmasnSalarVeTmTokenlarSiler
      description: ''
      parameters: []
      responses: {  }
      tags:
        - Endpoints
      security: []
  /api/auth/user:
    get:
      summary: 'Giriş yapmış kullanıcının bilgilerini getirir.'
      operationId: giriYapmKullancnnBilgileriniGetirir
      description: ''
      parameters: []
      responses:
        401:
          description: ''
          content:
            application/json:
              schema:
                type: object
                example:
                  message: Unauthenticated.
                properties:
                  message:
                    type: string
                    example: Unauthenticated.
      tags:
        - Endpoints
      security: []
  /api/auth/profile:
    put:
      summary: 'Kullanıcı profilini günceller.'
      operationId: kullancProfiliniGnceller
      description: ''
      parameters: []
      responses: {  }
      tags:
        - Endpoints
      security: []
  /api/roles:
    get:
      summary: ''
      operationId: getApiRoles
      description: ''
      parameters: []
      responses: {  }
      tags:
        - Endpoints
      security: []
    post:
      summary: ''
      operationId: postApiRoles
      description: ''
      parameters: []
      responses: {  }
      tags:
        - Endpoints
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                name:
                  type: string
                  description: ''
                  example: ut
                  nullable: false
                description:
                  type: string
                  description: ''
                  example: 'Illum id impedit enim nihil doloremque.'
                  nullable: true
                permissions:
                  type: array
                  description: 'The <code>id</code> of an existing record in the permissions table.'
                  example: null
                  items:
                    type: string
              required:
                - name
      security: []
  '/api/roles/{role_id}':
    get:
      summary: ''
      operationId: getApiRolesRole_id
      description: ''
      parameters: []
      responses: {  }
      tags:
        - Endpoints
      security: []
    put:
      summary: ''
      operationId: putApiRolesRole_id
      description: ''
      parameters: []
      responses: {  }
      tags:
        - Endpoints
      requestBody:
        required: false
        content:
          application/json:
            schema:
              type: object
              properties:
                name:
                  type: string
                  description: ''
                  example: null
                  nullable: false
                description:
                  type: string
                  description: ''
                  example: 'Vel enim rerum delectus.'
                  nullable: true
                permissions:
                  type: array
                  description: 'The <code>id</code> of an existing record in the permissions table.'
                  example: null
                  items:
                    type: string
      security: []
    delete:
      summary: ''
      operationId: deleteApiRolesRole_id
      description: ''
      parameters: []
      responses: {  }
      tags:
        - Endpoints
      security: []
    parameters:
      -
        in: path
        name: role_id
        description: 'The ID of the role.'
        example: 1
        required: true
        schema:
          type: integer
  /api/permissions:
    get:
      summary: ''
      operationId: getApiPermissions
      description: ''
      parameters: []
      responses:
        401:
          description: ''
          content:
            application/json:
              schema:
                type: object
                example:
                  message: Unauthenticated.
                properties:
                  message:
                    type: string
                    example: Unauthenticated.
      tags:
        - Endpoints
      security: []
    post:
      summary: ''
      operationId: postApiPermissions
      description: ''
      parameters: []
      responses: {  }
      tags:
        - Endpoints
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                name:
                  type: string
                  description: ''
                  example: et
                  nullable: false
                description:
                  type: string
                  description: ''
                  example: 'Earum quia sint amet vel iure excepturi aut.'
                  nullable: true
              required:
                - name
      security: []
  '/api/permissions/{permission_id}':
    get:
      summary: ''
      operationId: getApiPermissionsPermission_id
      description: ''
      parameters: []
      responses:
        401:
          description: ''
          content:
            application/json:
              schema:
                type: object
                example:
                  message: Unauthenticated.
                properties:
                  message:
                    type: string
                    example: Unauthenticated.
      tags:
        - Endpoints
      security: []
    put:
      summary: ''
      operationId: putApiPermissionsPermission_id
      description: ''
      parameters: []
      responses: {  }
      tags:
        - Endpoints
      requestBody:
        required: false
        content:
          application/json:
            schema:
              type: object
              properties:
                name:
                  type: string
                  description: ''
                  example: null
                  nullable: false
                description:
                  type: string
                  description: ''
                  example: 'At molestiae et quasi ut molestias.'
                  nullable: true
      security: []
    delete:
      summary: ''
      operationId: deleteApiPermissionsPermission_id
      description: ''
      parameters: []
      responses: {  }
      tags:
        - Endpoints
      security: []
    parameters:
      -
        in: path
        name: permission_id
        description: 'The ID of the permission.'
        example: 2
        required: true
        schema:
          type: integer
  /api/users:
    get:
      summary: ''
      operationId: getApiUsers
      description: ''
      parameters: []
      responses: {  }
      tags:
        - Endpoints
      security: []
  '/api/users/{user_id}':
    get:
      summary: ''
      operationId: getApiUsersUser_id
      description: ''
      parameters: []
      responses: {  }
      tags:
        - Endpoints
      security: []
    parameters:
      -
        in: path
        name: user_id
        description: 'The ID of the user.'
        example: 2
        required: true
        schema:
          type: integer
  /api/admin/contents:
    get:
      summary: 'Display a listing of the resource.'
      operationId: displayAListingOfTheResource
      description: ''
      parameters: []
      responses:
        401:
          description: ''
          content:
            application/json:
              schema:
                type: object
                example:
                  message: Unauthenticated.
                properties:
                  message:
                    type: string
                    example: Unauthenticated.
      tags:
        - Endpoints
      security: []
    post:
      summary: 'Store a newly created resource in storage.'
      operationId: storeANewlyCreatedResourceInStorage
      description: ''
      parameters: []
      responses: {  }
      tags:
        - Endpoints
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                title:
                  type: string
                  description: 'Must not be greater than 255 characters.'
                  example: guwexk
                  nullable: false
                body:
                  type: string
                  description: ''
                  example: nisi
                  nullable: false
                slug:
                  type: string
                  description: ''
                  example: esse
                  nullable: false
                is_active:
                  type: boolean
                  description: ''
                  example: false
                  nullable: false
              required:
                - title
                - body
                - slug
      security: []
  '/api/admin/contents/{content_id}':
    get:
      summary: 'Display the specified resource.'
      operationId: displayTheSpecifiedResource
      description: ''
      parameters: []
      responses:
        401:
          description: ''
          content:
            application/json:
              schema:
                type: object
                example:
                  message: Unauthenticated.
                properties:
                  message:
                    type: string
                    example: Unauthenticated.
      tags:
        - Endpoints
      security: []
    put:
      summary: 'Update the specified resource in storage.'
      operationId: updateTheSpecifiedResourceInStorage
      description: ''
      parameters: []
      responses: {  }
      tags:
        - Endpoints
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                title:
                  type: string
                  description: 'Must not be greater than 255 characters.'
                  example: fjwnutqacdjelymgwsm
                  nullable: false
                body:
                  type: string
                  description: ''
                  example: eligendi
                  nullable: false
                slug:
                  type: string
                  description: ''
                  example: null
                  nullable: false
                is_active:
                  type: boolean
                  description: ''
                  example: false
                  nullable: false
              required:
                - title
                - body
      security: []
    delete:
      summary: 'Remove the specified resource from storage.'
      operationId: removeTheSpecifiedResourceFromStorage
      description: ''
      parameters: []
      responses: {  }
      tags:
        - Endpoints
      security: []
    parameters:
      -
        in: path
        name: content_id
        description: 'The ID of the content.'
        example: 19
        required: true
        schema:
          type: integer
tags:
  -
    name: Endpoints
    description: ''
