openapi: 3.0.3
info:
  title: 'Larecta CMS API Documentation'
  description: 'Larecta CMS is a modern API system developed for content management. It includes core CMS functionalities such as user management, authorization, content creation and editing. The API provides a secure and efficient way to manage your content.'
  version: 1.0.0
servers:
  -
    url: 'http://localhost:8000'
paths:
  /api/auth/user:
    get:
      summary: 'Get user information.'
      operationId: getUserInformation
      description: ''
      parameters: []
      responses:
        200:
          description: ''
          content:
            application/json:
              schema:
                type: object
                example:
                  status: true
                  message: 'User information retrieved successfully'
                  data:
                    id: 1
                    name: 'John Doe'
                    email: john@example.com
                    email_verified_at: '2024-01-15T10:00:00.000000Z'
                    created_at: '2024-01-15T10:00:00.000000Z'
                    updated_at: '2024-01-15T10:00:00.000000Z'
                properties:
                  status:
                    type: boolean
                    example: true
                  message:
                    type: string
                    example: 'User information retrieved successfully'
                  data:
                    type: object
                    properties:
                      id:
                        type: integer
                        example: 1
                      name:
                        type: string
                        example: 'John Doe'
                      email:
                        type: string
                        example: john@example.com
                      email_verified_at:
                        type: string
                        example: '2024-01-15T10:00:00.000000Z'
                      created_at:
                        type: string
                        example: '2024-01-15T10:00:00.000000Z'
                      updated_at:
                        type: string
                        example: '2024-01-15T10:00:00.000000Z'
      tags:
        - Authentication
  /api/auth/register:
    post:
      summary: 'Creates a new user registration.'
      operationId: createsANewUserRegistration
      description: ''
      parameters: []
      responses: {  }
      tags:
        - Endpoints
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                name:
                  type: string
                  description: "User's full name. Maximum: 255 characters."
                  example: beatae
                  nullable: false
                email:
                  type: string
                  description: "User's email address. Maximum: 255 characters, must be unique."
                  example: liliane92@example.com
                  nullable: false
                password:
                  type: string
                  description: "User's password. Minimum: 6 characters."
                  example: "(92Q=6'{r+W]JU"
                  nullable: false
              required:
                - name
                - email
                - password
  /api/auth/login:
    post:
      summary: 'Authenticates user and creates token.'
      operationId: authenticatesUserAndCreatesToken
      description: ''
      parameters: []
      responses: {  }
      tags:
        - Endpoints
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                email:
                  type: string
                  description: 'Must be a valid email address.'
                  example: maye02@example.com
                  nullable: false
                password:
                  type: string
                  description: ''
                  example: culpa
                  nullable: false
              required:
                - email
                - password
  /api/auth/logout:
    post:
      summary: 'Logs out the user and deletes all tokens.'
      operationId: logsOutTheUserAndDeletesAllTokens
      description: ''
      parameters: []
      responses: {  }
      tags:
        - Endpoints
  /api/auth/profile:
    put:
      summary: 'Updates user profile information.'
      operationId: updatesUserProfileInformation
      description: ''
      parameters: []
      responses: {  }
      tags:
        - Endpoints
  /api/roles:
    get:
      summary: ''
      operationId: getApiRoles
      description: ''
      parameters: []
      responses:
        401:
          description: ''
          content:
            application/json:
              schema:
                type: object
                example:
                  message: Unauthenticated.
                properties:
                  message:
                    type: string
                    example: Unauthenticated.
      tags:
        - Endpoints
    post:
      summary: ''
      operationId: postApiRoles
      description: ''
      parameters: []
      responses: {  }
      tags:
        - Endpoints
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                name:
                  type: string
                  description: ''
                  example: ullam
                  nullable: false
                description:
                  type: string
                  description: ''
                  example: 'Error id sit laudantium dolorem est consequatur veniam neque.'
                  nullable: true
                permissions:
                  type: array
                  description: 'The <code>id</code> of an existing record in the permissions table.'
                  example: null
                  items:
                    type: string
              required:
                - name
  '/api/roles/{role_id}':
    get:
      summary: ''
      operationId: getApiRolesRole_id
      description: ''
      parameters: []
      responses:
        401:
          description: ''
          content:
            application/json:
              schema:
                type: object
                example:
                  message: Unauthenticated.
                properties:
                  message:
                    type: string
                    example: Unauthenticated.
      tags:
        - Endpoints
    put:
      summary: ''
      operationId: putApiRolesRole_id
      description: ''
      parameters: []
      responses: {  }
      tags:
        - Endpoints
      requestBody:
        required: false
        content:
          application/json:
            schema:
              type: object
              properties:
                name:
                  type: string
                  description: ''
                  example: null
                  nullable: false
                description:
                  type: string
                  description: ''
                  example: 'Odit nihil qui debitis voluptas labore debitis.'
                  nullable: true
                permissions:
                  type: array
                  description: 'The <code>id</code> of an existing record in the permissions table.'
                  example: null
                  items:
                    type: string
    delete:
      summary: ''
      operationId: deleteApiRolesRole_id
      description: ''
      parameters: []
      responses: {  }
      tags:
        - Endpoints
    parameters:
      -
        in: path
        name: role_id
        description: 'The ID of the role.'
        example: 1
        required: true
        schema:
          type: integer
  /api/permissions:
    get:
      summary: ''
      operationId: getApiPermissions
      description: ''
      parameters: []
      responses:
        401:
          description: ''
          content:
            application/json:
              schema:
                type: object
                example:
                  message: Unauthenticated.
                properties:
                  message:
                    type: string
                    example: Unauthenticated.
      tags:
        - Endpoints
    post:
      summary: ''
      operationId: postApiPermissions
      description: ''
      parameters: []
      responses: {  }
      tags:
        - Endpoints
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                name:
                  type: string
                  description: ''
                  example: est
                  nullable: false
                description:
                  type: string
                  description: ''
                  example: 'Quo ea est libero accusantium dicta animi voluptatem distinctio.'
                  nullable: true
              required:
                - name
  '/api/permissions/{permission_id}':
    get:
      summary: ''
      operationId: getApiPermissionsPermission_id
      description: ''
      parameters: []
      responses:
        401:
          description: ''
          content:
            application/json:
              schema:
                type: object
                example:
                  message: Unauthenticated.
                properties:
                  message:
                    type: string
                    example: Unauthenticated.
      tags:
        - Endpoints
    put:
      summary: ''
      operationId: putApiPermissionsPermission_id
      description: ''
      parameters: []
      responses: {  }
      tags:
        - Endpoints
      requestBody:
        required: false
        content:
          application/json:
            schema:
              type: object
              properties:
                name:
                  type: string
                  description: ''
                  example: null
                  nullable: false
                description:
                  type: string
                  description: ''
                  example: 'Similique nihil nostrum eius temporibus eveniet et officiis.'
                  nullable: true
    delete:
      summary: ''
      operationId: deleteApiPermissionsPermission_id
      description: ''
      parameters: []
      responses: {  }
      tags:
        - Endpoints
    parameters:
      -
        in: path
        name: permission_id
        description: 'The ID of the permission.'
        example: 2
        required: true
        schema:
          type: integer
  /api/users:
    get:
      summary: ''
      operationId: getApiUsers
      description: ''
      parameters: []
      responses:
        401:
          description: ''
          content:
            application/json:
              schema:
                type: object
                example:
                  message: Unauthenticated.
                properties:
                  message:
                    type: string
                    example: Unauthenticated.
      tags:
        - Endpoints
  '/api/users/{user_id}':
    get:
      summary: ''
      operationId: getApiUsersUser_id
      description: ''
      parameters: []
      responses:
        401:
          description: ''
          content:
            application/json:
              schema:
                type: object
                example:
                  message: Unauthenticated.
                properties:
                  message:
                    type: string
                    example: Unauthenticated.
      tags:
        - Endpoints
    parameters:
      -
        in: path
        name: user_id
        description: 'The ID of the user.'
        example: 2
        required: true
        schema:
          type: integer
  /api/admin/contents:
    get:
      summary: 'Display a listing of the resource.'
      operationId: displayAListingOfTheResource
      description: ''
      parameters: []
      responses:
        401:
          description: ''
          content:
            application/json:
              schema:
                type: object
                example:
                  message: Unauthenticated.
                properties:
                  message:
                    type: string
                    example: Unauthenticated.
      tags:
        - Endpoints
    post:
      summary: 'Store a newly created resource in storage.'
      operationId: storeANewlyCreatedResourceInStorage
      description: ''
      parameters: []
      responses: {  }
      tags:
        - Endpoints
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                title:
                  type: string
                  description: 'Must not be greater than 255 characters.'
                  example: j
                  nullable: false
                body:
                  type: string
                  description: ''
                  example: sit
                  nullable: false
                slug:
                  type: string
                  description: ''
                  example: quis
                  nullable: false
                type:
                  type: string
                  description: ''
                  example: sequi
                  nullable: true
                status:
                  type: string
                  description: ''
                  example: published
                  nullable: false
                  enum:
                    - draft
                    - published
                    - archived
                content:
                  type: string
                  description: ''
                  example: beatae
                  nullable: true
                meta:
                  type: string
                  description: 'Must be a valid JSON string.'
                  example: '["excepturi","magnam"]'
                  nullable: true
              required:
                - title
                - body
                - slug
                - status
  '/api/admin/contents/{content_id}':
    get:
      summary: 'Display the specified resource.'
      operationId: displayTheSpecifiedResource
      description: ''
      parameters: []
      responses:
        401:
          description: ''
          content:
            application/json:
              schema:
                type: object
                example:
                  message: Unauthenticated.
                properties:
                  message:
                    type: string
                    example: Unauthenticated.
      tags:
        - Endpoints
    put:
      summary: 'Update the specified resource in storage.'
      operationId: updateTheSpecifiedResourceInStorage
      description: ''
      parameters: []
      responses: {  }
      tags:
        - Endpoints
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                title:
                  type: string
                  description: 'Must not be greater than 255 characters.'
                  example: qyojocgjlxhejttaqvtazjfd
                  nullable: false
                body:
                  type: string
                  description: ''
                  example: voluptate
                  nullable: false
                slug:
                  type: string
                  description: ''
                  example: null
                  nullable: false
                is_active:
                  type: boolean
                  description: ''
                  example: false
                  nullable: false
              required:
                - title
                - body
    delete:
      summary: 'Remove the specified resource from storage.'
      operationId: removeTheSpecifiedResourceFromStorage
      description: ''
      parameters: []
      responses: {  }
      tags:
        - Endpoints
    parameters:
      -
        in: path
        name: content_id
        description: 'The ID of the content.'
        example: 2
        required: true
        schema:
          type: integer
tags:
  -
    name: Authentication
    description: ''
  -
    name: Endpoints
    description: ''
components:
  securitySchemes:
    default:
      type: http
      scheme: bearer
      description: 'You can retrieve your token by visiting your dashboard and clicking <b>Generate API token</b>.'
security:
  -
    default: []
